### PR TITLE
zeek-archiver/compress: Prevent command injection through filenames

### PR DESCRIPTION
**Pull request by awelzel**
Skimming the code it seemed log files created as follows could cause
interesting behavior:

    event zeek_init() {
      Log::create_stream(Foo::LOG, [$columns=Info, $path="test;uptime;touch x"]);
      Log::write(Foo::LOG, [$ts=current_time()]);
    }

This may not necessary be malicious behavior. Putting a `;` into a filename
could be considered valid (whether sensible or not). In that case, logs aren't
archived.

This patch proposes to `fork()` a separate child that connects stdin/stdout accordingly which ends up fairly complex.
Maybe there's an easy way to properly escape the filenames. So maybe a different approach is more suitable?

### CODE REVIEW

**Comment by jsiwek** [comment]
Would it be sufficient to wrap the filenames in single-quotes before passing to `system()` ?  E.g.

```diff
diff --git a/zeek-archiver.cc b/zeek-archiver.cc
index 6c3c128..43f322c 100644
--- a/zeek-archiver.cc
+++ b/zeek-archiver.cc
@@ -568,8 +568,8 @@ static int archive_logs()
			debug("Archive via compression: %s -> %s", src_file.data(), dst_file.data());

			std::string cmd = options.compress_cmd;
-			cmd += "<"; cmd += src_file.data();
-			cmd += ">"; cmd += tmp_file.data();
+			cmd += "<'"; cmd += src_file; cmd += "'";
+			cmd += ">'"; cmd += tmp_file; cmd += "'";

			auto res = system(cmd.data());

```

i.e. these are already filenames on disk, so just need to avoid having the shell interpret things in the name and instead always use literal values.  (Generally think we can assume these names are "trusted" in the first place, so yeah, it's maybe more a question of sensible vs. valid -- might be unaware of a legit use-cage, but personally wouldn't say it's sensible to put semi-colons or other weird stuff in these filenames, but sure, we can probably try to do something about it in terms of "technical validity").

**Comment by awelzel** [comment]
Hey Jon,

thanks for checking this out.

The quoting approach would require to at least quote `'` characters inside the filenames as well, otherwise one can terminate the quoting with an extra `'` in the filename. It seems what `shlex.quote` in Python does may be okay for bash/sh, but maybe not generally safe. Input from [Stackoverflow](https://stackoverflow.com/a/288071/9044112)...


> (Generally think we can assume these names are "trusted" in the first place, so yeah, it's maybe more a question of sensible vs. valid -- might be unaware of a legit use-cage, but personally wouldn't say it's sensible to put semi-colons or other weird stuff in these filenames, but sure, we can probably try to do something about it in terms of "technical validity")

I may have a bit of a stricter view here: I don't think the filenames should be trusted. Anyone who gains write access to the logs queue directory gains permissions to run commands as the user under which `zeek-archiver` runs.  Consider the permissions on the logs queue directory are configured too lax (everyone can write there) and `zeek-archiver` is running as root.

**Comment by jsiwek** [comment]
I'm on board: thanks for the patch + test-cases.

I made several adjustments during merge: b2d096961fe725dbe6b11cbfbed499c8377d7687
And also added a signal handler to cleanup the child-compression process on SIGTERM: 61d3c604c514c7f9d21d076dd0751964518b2f96

Can you double check what's in `master` to see if you notice anything that's still concerning?

**Comment by awelzel** [comment]
LGTM. Thanks for refining it. Great catch for the `0644` vs `0444` mode.

**Pull request merged**
