### PR TITLE
CI updates

### PR DESCRIPTION
**Pull request by ckreibich**
Companion to zeek/zeek#3502.

### CODE REVIEW

**Review by awelzel — APPROVED** [review]
Just throwing it out there: I wonder if we should move `zeek-archiver` into `zeek-aux` and place it next to `zeek-cut` (or somewhere in `zeek/zeek` directly).

Except for multi-logger support relatively recently, nothing significant happened in this repo since some 3 years except for the regular CI update churn.

(Don't get me wrong, I'm all for figuring out a better way to do the CI updates)

**Comment by ckreibich** [comment]
Yep, I'm all for it. I think we could move it to `zeek-aux` even if there were a lot more activity here. `zeek-aux` itself could use some love too — do we really maintain adtrace.c and rst.c at this point? — etc.

**Comment by JustinAzoff** [comment]
I used to use `rst`! Though from what I remember I had to dig up the actual script that drove it out of svn history, and that was 10+ years ago

**Comment by ckreibich** [comment]
Yeah we're not actually using it any more in the scripts.

Over the years I have looked it up on occasion for low-level socket and checksumming code. :-)

**Pull request merged**
